### ISSUE TITLE
FS 100 response to MOTO_MOTION_CTRL message incorrect.

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/motoman#1]
The robot id and sequence fields in the MOTO_MOTION_CTRL reply are not set correctly.  See the email snippet below for more details.

<snip>

On 12/06/2013 20:01, Zoss, Jeremy K. wrote:

> Gijs,
> 
> I was not involved in the earlier email chain, so I don't have a copy 
> of the Wireshark capture. When I look through the MotoPlus source 
> code, I think I can see where this reply is coming from. See
> fs100/MotoPlus/SimpleMessage.c:Ros_SimpleMsg_MotionReply()
> http://code.google.com/p/swri-ros-pkg/source/browse/trunk/motoman/fs100/MotoPlus/SimpleMessage.c#92.
> In the code, it looks like when a reply message is sent to anything 
> other than a MOTO_MOTION_CTRL message (type 2001), the robot_id and 
> sequence fields are set to -1. This probably comes across as 0xFFFFFFFF.

Yes, -1 interpreted as an unsigned would be 0xFFFFFFFF.

> I don’t know that this behavior was intended or not. In particular, 
> the tests at lines 106 and 112 seem redundant. I agree with you that 
> the expected reply to a JointTrajPtFull message should mirror the 
> robot_id and sequence from the incoming message. I think your 
> interpretation of the expected response is correct.

Looks like a copy/pasta error to me then. The 'else if' checks again for a ROS_MSG_MOTO_MOTION_CTRL, just as the 'if' before it did.

> This should be a simple 3-line change, but I’ll check with the Motoman
> author first to see if he has any objections.

Ok.

If I get the dissector in a good enough state, I'll push it to my github 
repo.

Gijs

**Comment by JeremyZoss** [comment]
Eric has released a fix already.  I will try to upload this weekend.

**Comment by JeremyZoss** [comment]
Fixed in 292b5cc
