### ISSUE TITLE
driver: unneeded ROS_ERROR in robot_state_interface?

### ISSUE THREAD

**Issue by pbeeson** [ros-industrial/motoman#113]
This may seem trivial, but I'm trying to eliminate as many ROS_ERROR messages as possible in my application, where remote ROS-newbies are using my software stack, and red error lines result in frequent issues back to me.  If people agree with my assessment below, I can create a patch, though it's a simple issue for anyone to change in a couple of minutes.

So, the ([Usuage Tutorial](http://wiki.ros.org/motoman_driver/Tutorials/Usage)) for motoman driver discusses needing the _controller_joint_names_ parameter (which works for the industrial-robot-sim and industrial-robot-client), but when using the motoman launch files, the motoman driver complains twice about a missing _topic_list_.   It looks like robot_state_interface and joint_trajectory_interface properly handles a missing _topic_list_ parameter (getJointGroup() fails) by using _controller_joint_names_, so then why the need to throw an ERROR in getJointGroup()?

I do see that the multi-group (non-version0) motoman_driver_joint_trajectory_action node requires the _topic_list_ parameter, but it's not even handling the return from getJointGroup().  So, the better solution would be to NOT put an error out to the user in getJointGroup() if _topic_list_ does not exist, but catch this and put an error out in motoman_driver_joint_trajectory_action for people that really do require this parameter for multigroup setups.

**Comment by gavanderhoorn** [comment]
I think changing the `ERROR` to a `WARN` or maybe even just an `INFO` would make sense in the case of `robot_state_interface`. It's confusing to see the error on the console, as it makes it seem like something is really wrong, while in reality things are not that dire.

As to `getJointGroups(..)` not printing the `ERROR` itself: I think I agree with this as well. Throwing an exception, or just returning `false` and letting the caller deal with that seems more logical, especially if falling back to `controller_joint_names` is an accepted (and already considered) flow of control.

An exception would allow for more fine-grained error reporting, but isn't really in-line with the rest of the code, style-wise.
