### ISSUE TITLE
mh5: incorrect link_t position

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#122]
It would seem `link_t` in the MH5 xacro macro is currently not at the correct position:

![rviz_screenshot_2016_08_24-16_15_07](https://cloud.githubusercontent.com/assets/4550046/17933889/17b929c0-6a16-11e6-96f2-f54538f29723.png)

It looks like this is a [transform issue](https://github.com/ros-industrial/motoman/blob/605ae9989036a925195c75b00846152c145ac5a1/motoman_mh5_support/urdf/mh5_macro.xacro#L164), and not related to the origin of the mesh.

**Comment by shaun-edwards** [comment]
@geoffreychiou, could you take a look at this one next week?

**Comment by gavanderhoorn** [comment]
This should be fixed with the merge of #173.

**Comment by shaun-edwards** [comment]
Actually it was only half fixed...now fully fixed in #175
