### ISSUE TITLE
sda10f_support: missing face in S-link (visual quality)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#125]
There appears to be a face (or multiple) missing in the mesh associated with `link_1_s` (the black area underneath the rounded upper part):

![sshot](https://cloud.githubusercontent.com/assets/4550046/18049703/1ecfe5fa-6dea-11e6-9dc1-a189e632d9b0.png)

This is the `motoman_axis_s.stl` file, in the `meshes/sda10f/visual` directory of the package.

Even though it is in a rather hard to reach location, missing faces are potentially problematic when using this mesh for collision detection, and thus should be fixed.

**Comment by EricMarcil** [comment]
@gavanderhoorn fixed it in the PR #327.  Please review...
