### ISSUE TITLE
installation: INFORM Code in DX200 ERROR!

### ISSUE THREAD

**Issue by BlazingForests** [ros-industrial/motoman#142]
Hi, guys

I am following this wiki http://wiki.ros.org/motoman_driver/Tutorials/indigo/InstallServer

I already installed the MotoROS in DX200, looks no problem.

When i installing the INFORM Code in DX200, ERROR!

DX200 show this ERROR

```
L:****) ERROR 3200 : NOP or END instruction not found (J:INIT_ROS
```

My DX200's version is 

```
DN2.05.00A-00
```

Does anyone know how to solve it?

THX

**Comment by gavanderhoorn** [comment]
Just to make sure: you did use the file from [motoman_driver/Inform/DX200/single_arm](https://github.com/ros-industrial/motoman/tree/jade-devel/motoman_driver/Inform/DX200/single_arm), correct?

**Comment by BlazingForests** [comment]
Hi, @gavanderhoorn Yes, I am sure.

**Comment by BlazingForests** [comment]
Even i modify the INIT_ROS, still ERROR

```
NOP
DOUT OT#(890) OFF
DOUT OT#(889) OFF
TIMER T=0.05
DOUT OT#(889) ON
WAIT OT#(890)=ON
DOUT OT#(890) OFF
END
```

**Comment by gavanderhoorn** [comment]
I'm pretty sure you can't just remove the header of jobs and expect things to work.

Perhaps an incompatibility was introduced recently, as `INIT_ROS.JBI` has been like that for a long time.

@ted-miller ?

**Comment by BlazingForests** [comment]
I think i fixed it.

I directly create INIT_ROS on pendant, It's OK, no problem.
Then i save this job to USB drive. As follows

```
/JOB
//NAME INIT_ROS
//POS
///NPOS 0,0,0,0,0,0
//INST
///DATE 2017/01/09 13:10
///ATTR SC,RW
///GROUP1 RB1
NOP
DOUT OT#(890) OFF
DOUT OT#(889) OFF
TIMER T=0.05
DOUT OT#(889) ON
WAIT OT#(890)=ON
DOUT OT#(890) OFF
END
```

THX

**Comment by ted-miller** [comment]
gavanderhoorn is correct that you cannot just remove the job header.  This is required when loading a job into the robot controller.

However, the most common reason for the error:
"_ERROR 3200 : NOP or END instruction not found_" is because of the line-endings.

The robot controller requires Windows-style line endings: <carriage return><line feed>

If you open the job in a Linux text editor (like gedit), it can change the line endings to eliminate the <carriage return>.  This will cause the Error 3200.

**Comment by gavanderhoorn** [comment]
Right, I thought it might be something like that.

@BlazingForests: if you cloned the `motoman` repository using `git`, then it could have automatically converted the line-endings to Unix. That could cause what @ted-miller described.

**Comment by BlazingForests** [comment]
@ted-miller 
Thank you very much.
I had think about the line-endings. But i think just directly create new job on pendant is the faster way to confirm.

Thank you for point this problem.

THX

**Comment by gavanderhoorn** [comment]
I'm going to close as this seems resolved. We're tracking the line-ending issue in #146.

@BlazingForests: please re-open if you feel this is not ok.

**Comment by BlazingForests** [comment]
@gavanderhoorn 
Thank you! No problem. I think we can remind people this problem.

**Comment by gavanderhoorn** [comment]
@BlazingForests: the *Troubleshooting* page on the ROS wiki for `motoman_driver` now also contains information on how to address the issue with line-endings you encountered. See [ERROR 3200: NOP or END instruction not found](http://wiki.ros.org/motoman_driver/Troubleshooting#ERROR_3200:_NOP_or_END_instruction_not_found).
