### ISSUE TITLE
driver: invert ctrlr parameter checking logic in SetupValidation

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#145]
As per comment of @ted-miller (https://github.com/ros-industrial/motoman/issues/144#issuecomment-271284110):

> I now realize that I display the alarms in the wrong order. If they don't have any parameters configured, they'll get alarms for all of the user-configurable parameters first. Then, after rebooting like 6 times, they'll finally get an alarm that says they are dead and need to contact Yaskawa.
> 
> I need to update the SetupValidation.__lib files to return the critical error codes first.

**Comment by ted-miller** [comment]
@gavanderhoorn 
See #148.

**Comment by gavanderhoorn** [comment]
Resolved in #148.
