### ISSUE TITLE
Are parameters setting and setup of YRC1000 for MotoROS the same as DX200? 

### ISSUE THREAD

**Issue by BlazingForests** [ros-industrial/motoman#170]
Hi, guys

Are parameters setting and setup of YRC1000 for MotoROS the same as DX200? 

Thank you!

**Comment by ted-miller** [comment]
Yes.  With the YRC1000 and DX200, you can enable the required settings in Maintenance Mode.
Section 2.4 of the wiki tutorial explains the details.  http://wiki.ros.org/motoman_driver/Tutorials/indigo/InstallServer

**Comment by BlazingForests** [comment]
@ted-miller Thank you!
