### ISSUE TITLE
Robot specific launch files are missing.

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/motoman#18]
Launch files specific to the different Motoman robots are missing.  The fanuc utilizes robot specific packages (which makes it much more user friendly).  

The robot specific files can be used to set parameters that would otherwise have to be set by the user.  This is not at all apparent and leads to issues/questions ( see: http://answers.ros.org/question/100916/setup-industrial-package-for-use-of-motoman-driver-interface-with-dx100-motoplus/ ).

**Comment by gavanderhoorn** [comment]
All support packages (in this repository at least) have variant specific launch files now.
