### ISSUE TITLE
wiki: link to MotoROS binaries in repository instead of attaching them

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#195]
Suggestion: let's link to the MotoROS binaries hosted here on Github from the wiki pages instead of attaching them.

By linking directly we can avoid having to keep the pages up-to-date, as users will automatically download the latest releases.

**Comment by gavanderhoorn** [comment]
If we're using the attachments to do controlled releases of the binaries we can/should of course keep doing that, but I'm not aware of such a policy.

**Comment by ted-miller** [comment]
I used attachments for two reasons.
- Many new users are not familiar with Github.  The web interface is weird and non-intuitive for downloading a single file. The wiki attachment is easier.
- If the default branch changes (kinetic-devel), then we'll have to update the wiki links anyway.

Having said that, it's not a big deal.  I don't care that much either way.

**Comment by gavanderhoorn** [comment]
> Many new users are not familiar with Github. The web interface is weird and non-intuitive for downloading a single file. The wiki attachment is easier.

we can directly link to the binaries like so: https://github.com/ros-industrial/motoman/blob/kinetic-devel/motoman_driver/MotoPlus/output/DX100/MotoRosDX100/MotoRosDX100.out?raw=true. Provided the path to the binary doesn't change, that link will always return the latest version of `MotoRosDX100.out` in the `kinetic-devel` branch.

That is the link to `v1.7.0` for DX100.

If we add tags to the repository for each MotoROS 'release', then we could use tags instead of the branch names or commit hashes, and we'd get urls like: https://github.com/ros-industrial/motoman/blob/0.3.5/motoman_driver/MotoPlus/output/DX100/MotoRosDX100/MotoRosDX100.out?raw=true (`0.3.5` is a `motoman_driver` tag, but it's the same idea).

> If the default branch changes (kinetic-devel), then we'll have to update the wiki links anyway.

that is true, but I expect that to happen a lot less than releasing new versions of MotoROS.

**Comment by gavanderhoorn** [comment]
We could also make use of Githubs [releases](https://github.com/ros-industrial/motoman/releases) system. But that would require some manual work ([docs](https://help.github.com/articles/creating-releases/)).

**Comment by gavanderhoorn** [comment]
:bellhop_bell: @ted-miller?

Would using the links I show in my previous comment be acceptable?

I'm just trying to find a way to be able to avoid having to manually update the wiki pages to track new releases.

**Comment by ted-miller** [comment]
Yeah. I'll fix the links.  I just forgot about this.

**Comment by ted-miller** [comment]
It is done.
