### ISSUE TITLE
sia5f joint_u and joint_b rotation sign error

### ISSUE THREAD

**Issue by tdl-ua** [ros-industrial/motoman#203]
As I ran the launch-file _test_sia5d.launch_ in _motoman/motoman_sia5d_support/launch/_, I noticed that the simulated behavior of the robot is not the same as the physical robot. The joints U and B rotate in the opposite direction when comparing simulation and physical robot. This issue also affects the planning and execution of trajectories with MoveIt!.

I have now made changes to the file _sia5d_macro.xacro_ and updated the file _sia5d_macro.urdf_ using xarco.py to fix the issue. I will create a pull request shorty that contains the changes made. 

It should be noted that our lab uses the sia5f robot version, where _f_ indicates the controller type FS100. Therefore, the behavior of the sia5d version could be correct when using the unchanged version of the urdf model.

**Comment by gavanderhoorn** [comment]
This was fixed in #204.
