### ISSUE TITLE
wiki: update links to motoros binaries on installation tutorial page

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#220]
From https://github.com/ros-industrial/motoman/issues/196#issuecomment-398357434:

> @ted-miller: we'll need to remember updating the links on the wiki on the [installation tutorial](http://wiki.ros.org/motoman_driver/Tutorials/indigo/InstallServer).

**Comment by ted-miller** [comment]
Done

**Comment by gavanderhoorn** [comment]
Awesome, thanks.
