### ISSUE TITLE
write/read IO digitals dx100

### ISSUE THREAD

**Issue by SinaiAranda** [ros-industrial/motoman#233]
Hi, I am trying read and write IO digitals of the robot in a dx100 controller, I use this [motoman_driver ](https://github.com/gavanderhoorn/motoman/tree/io_support_kinetic-devel_head_yuvraj)version already that have services for this but I have problems for see the services.

**Comment by gavanderhoorn** [comment]
The files you link to were specifically created for a multi-group robot setup. If you're not configuring things as such, the services won't show up.

But note also: that branch was created for someone with a specific setup that I was trying to help out. There is no guarantee it'll work for you.

Besides that, the IO support has not been universally integrated into `motoman_driver`.

**Comment by ctaipuj** [comment]
We just tested the motoman_driver version you mention and it works fine... on a fs100 controller (with a sda10f dual arm robot) . We were able to write to a network input (Eg. #25011). The write_io service only shows up when you correctly stablish communication with the controller.

**Comment by kctoayo88** [comment]
> We just tested the motoman_driver version you mention and it works fine... on a fs100 controller (whith a sda10f dual arm robot) . We were able to write to a network input (Eg. #25011). The write_io service only shows up when you correctly stablish communication with the controller.

@ctaipuj 
hello, could you tell me how to implement it or has any other method?

I follow that motoman_driver to create the files related to i/o service, but met the same problem with @sinaiaranda-CIDESI.

My robot is single arm robot MH5 with a fs100 controller.

**Comment by SinaiAranda** [comment]
Hi,
I use this [motoman_driver](https://github.com/sinaiaranda-CIDESI/motoman_driver/tree/io_motoman_driver).

**Comment by kctoayo88** [comment]
Thanks for your reply, but I still have a little confusion.

So, I just exchange the current version that I use to this version right?
And should I reinstalled any files on my controller?

If It really works, it would be nice to me.

**Comment by ctaipuj** [comment]
Hi, @kctoayo88 sorry for the delayed response. See [this package](https://github.com/ctaipuj/lenny_motoman/tree/master/motoman_variables) about the implementation.

**Comment by gavanderhoorn** [comment]
I'm going to close this, as #355 is going to address this.
