### ISSUE TITLE
Wiki page is ambiguous: can MotoROS be used with HC10 or not?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#243]
From [wiki/motoman_driver - Compatibility with collaborative robots (HC series)](http://wiki.ros.org/motoman_driver#Compatibility_with_collaborative_robots_.28HC_series.29):

> Please note that the MotoROS application is **not compatible with the Human Collaborative features** of the HC series robots at this time.

But it then goes on to say (in the next sentence):

> The MotoROS application can be installed, but only after disabling the collaborative features. Refer to Alarm 8003-8 on the Troubleshooting page for more information. 

These two sentences seem to contradict each other, and I seem to remember @ted-miller explaining that MotoROS should be considered incompatible with the HC10 robots.

**Comment by ted-miller** [comment]
The ruling on this has changed a few times...

As of today, the wiki is incorrect. The HC10 is not compatible with ROS. I will update the wiki on Monday.

However, there is work being done right now to make it compatible. We still need to do final validation of the safety features before releasing.

**Comment by AndyZe** [comment]
I updated the wiki for now.

**Comment by gavanderhoorn** [comment]
Ok.

Thanks @AndyZe. Diff [here](http://wiki.ros.org/action/info/motoman_driver?action=diff&rev2=30&rev1=27).
