### ISSUE TITLE
motoman_driver compile warnings when using -Wall 

### ISSUE THREAD

**Issue by dambrosio** [ros-industrial/motoman#260]
Various compile warnings when compiling with `-DCMAKE_CXX_FLAGS=-Wall -DCMAKE_C_FLAGS=-Wall`.

Fix warnings related to:

- [x] Fix warnings related to: comparison between signed and unsigned integer expressions [-Wsign-compare]
  - [x] Update ROS console logs to use %lu instead of %d now that for loop index variable will be of type `size_t` instead of `int`

- [x] Fix warnings related to: no return statement in function returning non-void [-Wreturn-type]
  - [x] Return value should be based on each call to create_messages() inside for-loop, probably want to return false if any of the `create_messages` function call retturns false

I have fixes for these and can create a PR for these in the next day or so.

**Comment by gavanderhoorn** [comment]
Closing as #388 was merged.
