### ISSUE TITLE
Add roslint_add_test() to motoman_driver and fix roslint errors

### ISSUE THREAD

**Issue by dambrosio** [ros-industrial/motoman#262]
`roslint_cpp()` is included in the `motoman_driver` package but has 2290 lint errors. The lint errors can be viewed by manually running `catkin_make roslint_motoman_driver`. These lint errors are masked because `roslint_add_test()` is not included in the CMakeLists file. 

I propose the following updates/fixes:

- [x] Fix all lint errors in the `motoman_driver` package 
- [x] Add `roslint_add_test()` to `if(CATKIN_ENABLE_TESTING)`
- [x] Verify roslint unit tests pass by running `catkin_make run_tests`

**Comment by gavanderhoorn** [comment]
Closing as #387 was merged.
