### ISSUE TITLE
motoman sda10f [ERROR] [1531987897.956109]: Start and End position joint_names mismatch

### ISSUE THREAD

**Issue by khalilibrahim** [ros-industrial/motoman#267]
When, I sent position for each joint of motoman sda10f like
`rosrun motoman_driver move_to_joint.py "[1.2114869356155396, 1.9079313278198242, 1.724528431892395, 0.7935540676116943, 1.1871036291122437, 0.25184622406959534, 0.16729415953159332]" `
results in:

```
[ERROR] [1531987897.956109]: Start and End position joint_names mismatch
[ERROR] [1531987897.957380]: Unable to move to commanded position. Aborting.
Traceback (most recent call last):
 File "/home/bsg/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 136, in <module>
    main(sys.argv[1:])
  File "/home/bsg/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 130, in main
    move_to_joint(end_pos, duration)
  File "/home/bsg/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 69, in move_to_joint
    traj = build_traj(get_cur_pos(), end_pos, duration)
  File "/home/bsg/catkin_ws/src/motoman/motoman_driver/src/move_to_joint.py", line 25, in build_traj
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

```
anyone help me

**Comment by gavanderhoorn** [comment]
I've logged an issue for the `TypeError` (#270), but I'm not sure this would ever work: an SDA robot has at least 2*7 joints and you only supply 7 values.

---

Edit: I'm actually not sure this script works with multi-group systems. It's from before my time, so I'd have to verify this.

**Comment by gavanderhoorn** [comment]
Was this resolved, or are you no longer interested in it?

**Comment by khalilibrahim** [comment]
Dear  G.A. vd. Hoorn,

Yes I solved now

**Comment by gavanderhoorn** [comment]
If you did, it would be good to know how.

What changes did you make?

**Comment by khalilibrahim** [comment]
I need to use STOMP planner insted of the OMPL in my package motoman_sda10f
I follow all instruction in https://github.com/ros-industrial/industrial_moveit but i fail to loading planner STOMP with my package.

**Comment by gavanderhoorn** [comment]
How is this related to the issue you reported here about the `move_to_joint.py` script?
