### ISSUE TITLE
Melodic Release

### ISSUE THREAD

**Issue by Mitch-Woodside** [ros-industrial/motoman#285]
**Motivation:**
It appears that Kinetic is the latest supported ROS distribution for the Motoman drivers. I have some need to use these drivers with the Melodic distribution.

**Questions:**
1. Is there any plan/desire to create an updated version of the drivers for Melodic?
2. If so, would this be a relatively simple task (just time consuming)?
3. What would be some expected difficulties in creating a Melodic version of the drivers?

**Comment by gavanderhoorn** [comment]
> It appears that Kinetic is the latest supported ROS distribution for the Motoman drivers.

Nuancing a bit: that is the latest release for which binary packages are available. That is something else.

I routinely build the packages in this repository on Melodic, and no changes are required.

> Is there any plan/desire to create an updated version of the drivers for Melodic?

Can you clarify what you mean by "updated version"?

**Comment by Mitch-Woodside** [comment]
> Nuancing a bit: that is the latest release for which binary packages are available. That is something else.

Ah, thanks for the clarification.

> I routinely build the packages in this repository on Melodic, and no changes are required.

I was basing my question on #202 and your answer to this older ROS answers question: https://answers.ros.org/question/242688/how-to-install-a-package-from-an-old-distro/?answer=242699#post-id-242699 

I was under the impression that there might be large changes that needed to be made to the source in order to get it to build correctly in Melodic. It appears that this is not the case.

> Is there any plan/desire to create an updated version of the drivers for Melodic?

I was referring to a new branch (melodic-devel or something) with updated source code.

**Comment by gavanderhoorn** [comment]
> > Nuancing a bit: that is the latest release for which binary packages are available. That is something else.
> 
> Ah, thanks for the clarification.

I was a bit too fast with my answer: we haven't actually made binary packages available for Kinetic.

> > I routinely build the packages in this repository on Melodic, and no changes are required.
> 
> I was basing my question on #202 and your answer to this older ROS answers question: https://answers.ros.org/question/242688/how-to-install-a-package-from-an-old-distro/?answer=242699#post-id-242699

That ROS Answers Q&A is a very generic description of what *may* be needed to get a package working with a new ROS release.

The ROS APIs we're using in `motoman_driver` have been stable for a very long time, and there are no significant/relevant changes between Indigo/Kinetic/Melodic that any changes are required to be able to use `motoman_driver` with Melodic.

> I was referring to a new branch (melodic-devel or something) with updated source code.

I'd understood that, but I was specifically wondering which updates you were referring to.

**Comment by Mitch-Woodside** [comment]
> I'd understood that, but I was specifically wondering which updates you were referring to.

"Updated Version" was probably the wrong terminology. I wasn't referring to any update or PR specifically, just a stable version of the drivers for Melodic. Which it appears that this is.

Thanks for the prompt feedback. The discussion has answered/clarified all of my questions.
