### ISSUE TITLE
Support Request for YRC1000 GP88

### ISSUE THREAD

**Issue by EricMarcil** [ros-industrial/motoman#288]
From https://github.com/ros-industrial/motoman/pull/277#issuecomment-527829509:
> I am currently working on basic GP88 support and would like to add the correct efforts there as well. Are these YRC1000 parameter charts available for download anywhere, or could you post the values for the GP88?

**Comment by EricMarcil** [comment]
I didn't want to post the GP88 information on #277 which is related to the GP180 to avoid any confusion.  The requested information is below:
![image](https://user-images.githubusercontent.com/4691677/64280137-83e06300-cf1e-11e9-996b-df1a0db611bd.png)

**Comment by cjue** [comment]
Thank you, now I only need to fix my collision meshes for my GP88 PR.

**Comment by gavanderhoorn** [comment]
I'll close this as we have an open PR that adds support and the (initial) question by @cjue has been answered.
