### ISSUE TITLE
Smaller collision models

### ISSUE THREAD

**Issue by Doomerdinger** [ros-industrial/motoman#394]
Is there any community desire for optional smaller (as in number of vertices/faces, not psychical volume) collision meshes?

Some of the use cases I encounter rely heavily on running collision checking a _lot_.
I've seen significant timing improvements by going in and manually tweaking the collision meshes to use fewer vertices and faces.

The drawback being that the collision meshes don't reflect the bounds of visual robot quite as nicely (it always covers everything the more true to life mesh does for safety, but it also encloses additional volume potentially hindering some more close call checks.)

If done intelligently, very little is lost. I have an example of where I have done this for the Universal Robot UR10e [here](https://github.com/path-robotics/universal_robot/tree/melodic-devel-staging/ur_description/meshes/ur10e/collision). I created minimalized collision meshes, as well as alternative minimalized collision meshes which are also convex hulls (if the first iteration was already a convex hull, only the convex hull file is listed). We don't really use the non-convex hull ones at this point, just figured I'd clarify the difference.

It is likely that I end up making something similar for Yaskawa arms we use. If there is no desire for these files, I will keep them out of any PRs I make.

It does make a bit more sense with the UR arms since you can change the models being used with a configuration file, whereas currently in this project if someone wanted to use the alternative meshes they would have to change the macro itself, but it wouldn't surprise me if people still found them of some use.

**Comment by cjue** [comment]
Smaller collision models are definitely interesting. I just want to point out that the GP4, GP7 and GP8 have their link2 "hollowed out" in a way that allows for more movement of joint3. A convex hull of link2 will therefore significantly restrict the range of motion of that joint, as shown here: https://github.com/ros-industrial/motoman/pull/433#issuecomment-988610550

Edit: convex hull, of course

**Comment by gavanderhoorn** [comment]
> A complex hull [..]

I believe you mean *convex* hull.

See related discussion here: https://github.com/ros-industrial/fanuc/issues/65 and https://github.com/ros-industrial/fanuc_experimental/issues/34.

Creating lower-poly geometry without sacrificing quality is rather difficult, especially with curvy meshes, like most (newer) industrial robots include.

**Comment by Doomerdinger** [comment]
@gavanderhoorn Yes, when I have done it I have done it by hand and it is time consuming.
Given that I may be doing this process for a select number of robots anyway, I was mainly curious if there was any desire for me to put the lower poly models in a PR in some capacity.
