### ISSUE TITLE
Package SIA20D_Mesh_arm_navigation is not following naming conventions

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#4]
Upon invoking `catkin_make` with the `motoman` stack in the workspace shows:

> WARNING: Package name "SIA20D_Mesh_arm_navigation" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.

**Comment by shaun-edwards** [comment]
Fixed in pull request #15
