### ISSUE TITLE
Inertial Tags for GP12 and MH12

### ISSUE THREAD

**Issue by kumar10725** [ros-industrial/motoman#416]
Inertial and mass tags are missing from the all the urdf models. Without these it is not possible to run the dynamic simulations for the robots, such as estimation of required torque to move an object. Is there any way to obtain those tags? or support will be missing for these tags?

**Comment by EricMarcil** [comment]
At this time, Yaskawa doesn't want to publicly publish those values.  To obtain them, you'll need to sign a Non-Discloser Agreement with your local Yaskawa representative.
You can contact me for the America or if you have difficulty figuring out your local representative at: 
eric.marcil@motoman.com

**Comment by kumar10725** [comment]
@EricMarcil After half a year of discussion with our local representative. They have denied any knowledge of such parameters. I have sent you an email from my work email. We are willing to sign a NDA if necessary.

**Comment by EricMarcil** [comment]
Please send me your information and the local Yaskawa representative that you have contacted at:
eric.marcil@motoman.com 
I will see what I can do to help.

**Comment by kumar10725** [comment]
@EricMarcil  I have sent you an email with the requested details. Thank you very much for your help.

**Comment by EricMarcil** [comment]
I've contacted the local Yaskawa representative and they will proceed with establishing the NDA.  Once that is done, I will be able to send the information.

For people that may run into similar situation in the future, some local Yaskawa representative might not be aware of ROS and how to get Kinematic information.  Please direct them to me at:  eric.marcil@motoman.com
I'll be able to explain that we only need them to put in place the NDA and that I will take care of the support afterward.
