### ISSUE TITLE
todo: update the usage tutorial

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/motoman#431]
The current content instructs users to use `motoman_driver` directly instead of using the (convenience) `.launch` files in the support packages.

It also still references `move_to_joint.py` which was removed in #333 and should not be used any more.

Manually setting `controller_joint_names` is also not something we should instruct users to do.

**Comment by adhitir** [comment]
I also recommend adding some instructions or examples on actually being able to interface with the robot.  An alternative to the move_to_joint example code.  Currently I'm not sure how to actually actuate the robot without attempting to setup a MoveIt! interface.

**Comment by gavanderhoorn** [comment]
Done in [diff&rev2=18&rev1=17](http://wiki.ros.org/action/info/motoman_driver/Tutorials/Usage?action=diff&rev2=18&rev1=17).
