### ISSUE TITLE
Add support for DX200 controller

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/motoman#44]
Blocking on PR #42, #43 and ros-industrial/industrial_core#82.
- [ ] Update launch files in driver package to support new controller type (add new controller specific launch file and verify byte ordering)
- [ ] Update wikis

**Comment by gavanderhoorn** [comment]
Is this still a TODO item @shaun-edwards ?

**Comment by gavanderhoorn** [comment]
DX200 support was added in #43 (MotoROS v1.2.0).
