### ISSUE TITLE
Joint naming convention

### ISSUE THREAD

**Issue by ted-miller** [ros-industrial/motoman#443]
I received a support request from a user who is getting the error `Failed to find topic_list parameter`. Following the advice from [here ](https://answers.ros.org/question/272045/support-motoman-yaskawa-gp-7-model/) and [here](https://github.com/ros-industrial/motoman/issues/235), we determined that `controller_joint_names` was not set correctly.

It seems that naming convention changed at some point to include the joint number. (`joint_s` to `joint_1_s`)

This is problematic because [the usage tutorial](http://wiki.ros.org/motoman_driver/Tutorials/Usage) doesn't show the new convention. 
Looking through the various support packages, some older robot models (such as MH5) are still using the old convention.

Which is better:
1. Update the tutorial to show both possible methods and advise the user to check the yaml file first.
2. Update the older packages to the new convention and then change the tutorial. (Are there any consequences to update the older packages to use the new convention?)

**Comment by acbuynak** [comment]
+1 for updating older packages to the new convention, but it may be prudent to note the old convention in the tutorial if people reference older forks of the support package.

I work with an MH5 (long-variant) on a daily basis, but understand them to be less common. And have an old open PR #380 which updated multiple things with the MH5 support package including the change in naming convention.
