### ISSUE TITLE
request - inertia, dynamics, & transmission elements in gp4 URDF for use in ROS/Gazebo physics simulation

### ISSUE THREAD

**Issue by adamlouis** [ros-industrial/motoman#469]
Hi!

I am trying to simulate the GP4 arm in [Gazebo](https://gazebosim.org/tutorials/?tut=ros_urdf) + ROS tools. 

The [GP4 URDF in this repo](https://github.com/ros-industrial/motoman/blob/kinetic-devel/motoman_gp4_support/urdf/gp4_macro.xacro) contains:

- geometry
- collisions
- joint relationships

but **does not** have

- `<inertia>` tags on links
- `<dynamics>` tags on joints
- top-level `<transmission>` tags for control

For context, see:
- Gazebo URDF requirements: https://gazebosim.org/tutorials/?tut=ros_urdf
- Gazebo Transmission & Control requirements: http://gazebosim.org/tutorials/?tut=ros_control
- URDF transmission docs: https://wiki.ros.org/urdf/XML/Transmission
- URDF link docs: https://wiki.ros.org/urdf/XML/link
- URDF joint docs: https://wiki.ros.org/urdf/XML/joint

I noticed that the [`sia10d` URDF file in this repo](https://github.com/ros-industrial/motoman/blob/9ade90acfe5835ca38fddcf6ac9cf589a452f449/motoman_sia10d_support/urdf/sia10d_macro.xacro#L47) **does** have `<inertia>` tags.

But no URDF file in this repo has `<dynamics>` or `<transmission>` tags.

I am working concurrently with a different arm from a different manufacturer -- here's [an example of a URDF file that contains all of those fields](https://github.com/Interbotix/interbotix_ros_manipulators/blob/main/interbotix_ros_xsarms/interbotix_xsarm_descriptions/urdf/px150.urdf.xacro): `<inertia>`, `<dynamics>`, `<transmission>`.

So, any chance you can add  `<inertia>`, `<dynamics>`, or `<transmission>` to the [GP4 URDF](https://github.com/ros-industrial/motoman/blob/kinetic-devel/motoman_gp4_support/urdf/gp4_macro.xacro) here?

**Comment by gavanderhoorn** [comment]
I'd refer you to two recent discussions about the same topic: #322 and #416.

From what I've understood, it's unlikely we'll add them.

The ones in the SIA10D model are approximations (and most likely bad ones).

I'll leave this open and wait for confirmation from @EricMarcil, but from the previous two issues I expect my answer to be correct.
