### ISSUE TITLE
Dual arm capability release plan

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/motoman#47]
PR #42 & #43 add dual arm control capability to the Motoman packages.

PR #43 contains all changes required for the motoplus/inform (controller side) software
PR #42 contains all changes required for the ROS (pc) software

Before rolling out this capability into the Hydro release, careful consideration must be given to how it could affect the current installations.  For example, the controller side software must be matched with appropriate launch parameters on the ROS side (launch parameters enable the ROS side to be backwards compatible).  If this is not done correctly, the system could fail to operate after a debian upgrade (with no warning to the user).  To address this, a two step release is planned.  

The first release, an upgrade to Hydro, will support both controller side server software versions.  
- All existing, single arm, robots will utilize the "old" (v1.1) by default software to ensure they continue to work when software is upgraded.
- Any new, dual/single arm, robots will utilize the "new" (v1.2) software by default
- Any new/custom robots created by users will be forced to utilize v1.2 (v1.1 sources/binaries will not be available).
- ROS side software will be configured via launch parameter to work with v1.1 or v1.2 software.
- Initially software will be released as source only (from the hydro-devel branch) to work out any unforseen issues.  A debain will only be released if a clean upgrade path can be assured (remains to be seen).
- A wiki will be created to describe the process for creating a dual arm setup (requiring the installation of software from source).

The second release, an Indigo release (~3 months), will only support v1.2 controller side software.
- All robots will utilize v1.2 software (provisions to use v1.1 will be turned off by default or totally removed).
- Wikis will be updated to reflect new installation/configuration procedures for v1.2 software.

**Comment by gavanderhoorn** [comment]
This was handled with the introduction of the `version0` parameter, that was later removed in #89.

Outstanding issues should be reported in new bug reports.
