### ISSUE TITLE
Dual Arm Operation Error

### ISSUE THREAD

**Issue by josephbhlee** [ros-industrial/motoman#473]
I have tried to operate dual arms at the same time, but failed.
//////////////////////////////////
1.Main Source Code
 std::vector<double> ppoints[2];
  std::vector<double> pvelocities[2];

  //Use current pose as first trajectory point
  ppoints[0] = readJointAngles();
  pvelocities[0] = readJointVelocities();
  
  //Use goal for position and 0 for velocity of second trajectory point
  ppoints[1].assign(goal,goal+15);
  pvelocities[1].assign(15,0.0);
  double d_msg[2] = {0,duration};

  control_msgs::FollowJointTrajectoryGoal msg = create_goal_message(ppoints, pvelocities,2,d_msg);

  sendJointTrajectory(msg);

2.Error Message
-. Invalid number of joint
-. Invalid trajectory. Not sent
///////////////////////////////
When I tried to operate each part(left arm, right arm and Torso), there was no error.

Can you guide me to operate dual arms at the same time?

**Comment by gavanderhoorn** [comment]
There's already #475, let's not duplicate that in an issue here.
