### ISSUE TITLE
Robot not enabled not causing joint_trajectory_action to fail

### ISSUE THREAD

**Issue by akashjinandra** [ros-industrial/motoman#486]
https://github.com/ros-industrial/motoman/blob/4c5e6afcaa53174b48ce39852768dfbe137f227d/motoman_driver/src/joint_trajectory_streamer.cpp#L429
Hello I'm wondering if anybody else see's this. I'm running Ubuntu 18 with ROS melodic. But if you are sending a trajectory and the robot is not enabled. I.E you didn't call the robot_enable service. It doesn't seem like the joint trajectory action actually stops running, it just hangs. The only solution seems to be having moveit monitor the trajectory and then it catches this issue. 

Is there anyway to know catch this happening besides using the moveit trajectory execution manager?

**Comment by gavanderhoorn** [comment]
It's a bit of a work-around (from the action client / MoveIt perspective), but `RobotStatus.motion_possible` will not be `true` unless you've called `robot_enable` first.

To make the action server deal with this a bit more intelligently, we'd have to see whether ros-industrial/industrial_core#271 already solves this (as `motoman_driver` depends on it), or whether we need to port that PR over to the `motoman_driver`-specific versions of the involved files.

That would make the action server reject goals unless MotoROS reports it's ready to execute them.
