### ISSUE TITLE
Setting workspace bounds

### ISSUE THREAD

**Issue by adhitir** [ros-industrial/motoman#494]
What is the best way to set hard workspace limits on the motoman hc10dt?
The inverse kinematics solutions sometimes lead to configurations that take move the joints of the robot and make it collide with the floor. Obviously, I wish to avoid this as its really hard to move the robot out of a collided pose. How can I set hard workspace bounds for the robot, not for the end-effector in task space but to avoid joint collisions with the floor.

**Comment by EricMarcil** [comment]
You can setup spatial limits with the Functional Safety Unit (FSU).  
Please refer to the related manuals:
https://www.motoman.com/getmedia/53EE5B5C-74C0-44BC-B8C9-96A751B7ED41/178949-1CD.pdf.aspx?ext=.pdf
