### ISSUE TITLE
MPP3H delta kinematics support

### ISSUE THREAD

**Issue by simonschmeisser** [ros-industrial/motoman#496]
Would it be possible to extend/modify this driver to support the MPP3H or similar delta kinematics? I assume control would be directly in cartesian space then?

Do you have that lying around as well @gavanderhoorn ? :wink:

**Comment by gavanderhoorn** [comment]
https://github.com/ros-industrial/motoman_experimental/pull/20

I can't say anything as-to the state of it, so if you can test it and can verify the functionality we may be able to actually get it merged.
