### ISSUE TITLE
Unwanted motion when switching pendant mode

### ISSUE THREAD

**Issue by EricMarcil** [ros-industrial/motoman#567]
If the pendant mode switch is turned during the ROS motion, the robot stops.  When the playback is re-enabled and the mode switch back to Remote mode, the robot moves because data in the motion queue was not cleared.

**Comment by cjue** [comment]
This is fixed and can be closed now, can't it? https://github.com/ros-industrial/motoman/pull/568#issuecomment-1783109730

**Comment by EricMarcil** [comment]
@cjue Yes, I will close.
