### ISSUE TITLE
Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111): MOTOMAN Driver

### ISSUE THREAD

**Issue by MohamedOmar2014** [ros-industrial/motoman#578]
Hello, I'm working on MA-1400 robot with DX-100 controller. I have installed the motoman packages on ubuntu 20.04 and ROS neotic. 
I have followed the instructions in https://wiki.ros.org/motoman_driver/Tutorials/Usage.

After starting the driver, I got he following error:

```
[ERROR] [1703353479.806916846]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[ERROR] [1703353479.812421194]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[ WARN] [1703353479.812605071]: Not connected, bytes not received
[ERROR] [1703353479.812731196]: Failed to receive message length
[ERROR] [1703353479.812871423]: Failed to receive incoming message
[ WARN] [1703353479.812991339]: Send failure, no callback support
[ERROR] [1703353479.820512152]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[ WARN] [1703353479.821230674]: Unable to read velocity limits from 'robot_description' param.  Velocity validation disabled.
[ERROR] [1703353479.824602270]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[FATAL] [1703353479.826375655]: Failed to connect
[ERROR] [1703353479.835195004]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
process[joint_trajectory_action-4]: started with pid [71405]
[ERROR] [1703353480.085480484]: Timeout connecting to robot controller.  Send new motion command to retry.
[ WARN] [1703353480.862728526]: Trajectory state not received for 1.000000 seconds
[ERROR] [1703353484.813898216]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
[ WARN] [1703353484.814005807]: Not connected, bytes not received
[ERROR] [1703353484.814076188]: Failed to receive message length
[ERROR] [1703353484.814148783]: Failed to receive incoming message
[ WARN] [1703353484.814217250]: Send failure, no callback support
[ERROR] [1703353489.815142831]: Failed to connect to server, rc: -1. Error: 'Connection refused' (errno: 111)
```

How can I solve that issue?

Also, their is no support package for MA-1400 robot. I have the URDF of this robot, can I copy the support package of MA-2010 and modify it for my robot. will that work?

**Comment by gavanderhoorn** [comment]
The connection errors seem to suggest MotoROS is not running on the DX100 -- or you're not providing the correct IP address to `motoman_driver`.

Assuming you're using the correct IP address:

- did you install the `.out` file on your controller?
- do you have a MotoPlus runtime license on that controller (as [mentioned on the driver's wiki page](https://wiki.ros.org/motoman_driver#MotoPlus_Runtime_License))?
- has your controller been configured correctly for MotoROS?

if the answer to any of these questions is *no*, then the errors you report are what we would expect to see.

> Also, their is no support package for MA-1400 robot. I have the URDF of this robot, can I copy the support package of MA-2010 and modify it for my robot. will that work?

Probably, yes.

If you'd like to have us review your changes, I'd suggest forking this repository, adding your MA-1400 support package, committing it and then opening a pull request here.
