### ISSUE TITLE
build fails: motoman_driver missing motoman_msgs dependencies

### ISSUE THREAD

**Issue by JeremyZoss** [ros-industrial/motoman#62]
Clone `motoman` repo to a bare catkin workspace, with no pre-installed `motoman` packages.  Run `catkin_make`, and build fails with the following error:

```
In file included from /home/ros-industrial/ros/src/motoman/motoman_driver/src/industrial_robot_client/joint_relay_handler.cpp:37:0:
/home/ros-industrial/ros/src/motoman/motoman_driver/include/motoman_driver/industrial_robot_client/joint_relay_handler.h:47:45: fatal error: motoman_msgs/DynamicJointsGroup.h: No such file or directory
 #include "motoman_msgs/DynamicJointsGroup.h"
                                             ^
```

Looks like the `CMakeLists.txt` in `motoman_driver` is missing some dependencies on `motoman_msgs` targets.  I confirmed that `motoman_msgs` is not being built prior to the error, and that the message header files are not being generated.

I have a fix with the required dependencies added, and will submit a pull-request shortly.

**Comment by gavanderhoorn** [comment]
Fixed in #63.
