### ISSUE TITLE
ROS launch tests fail on indigo-devel branch

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/motoman#74]
ROS launch test fail under indigo because the "version0" argument is not set by the calling launch files.  "version0" allows indigo client nodes to be run with a pre-indigo robot server.

**Comment by gavanderhoorn** [comment]
Not really surprising, but this is also seen in the ROS buildfarm [devel job](http://build.ros.org/job/Idev__motoman__ubuntu_trusty_amd64/lastCompletedBuild/console#console-section-3).

**Comment by gavanderhoorn** [comment]
Seeing as the tests now pass again (see [here](http://build.ros.org/job/Idev__motoman__ubuntu_trusty_amd64/) for the buildfarm job fi), this can be closed.
