### ISSUE TITLE
Update FS100/DX100 related documentation

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/motoman#8]
The FS100(groovy_devel) and DX100(groovy) were merged when the motoman controller side code became compatible with the DX100.  The following pages will have to be updated to reflect that change:

http://ros.org/wiki/fs100
http://ros.org/wiki/dx100
http://ros.org/wiki/motoman/Tutorials

**Comment by gavanderhoorn** [comment]
Is this still an open issue?

**Comment by gavanderhoorn** [comment]
The referenced pages have all been updated to either mention deprecation of the `fs100` and `dx100` packages, point to the new packages and / or make use of newer driver versions.
