### ISSUE TITLE
Controller not in REMOTE mode (5005)

### ISSUE THREAD

**Issue by ThomasTimm** [ros-industrial/motoman#9]
The MotoPlus application looks at the internal signal #50056 to detect if the pendant is in REMOTE mode. On European FS100 (or at least the one I have here in Denmark), the signal does not change when the key is turned to REMOTE. The control signal #80011 does on the other hand change.

Eric Marcil have verified this and mailed me a recompiled version where the control signal #80011 is used to detect wether the pendant is in REMOTE mode, but the change does not seem to have propagated to github yet. 
Please remember to include the change in this official version as well, to make this great package usable in Europe as well.

**Comment by JeremyZoss** [comment]
Shaun's been working on [reorganizing](https://github.com/ros-industrial/motoman/tree/dx100_driver_update) the motoman stack to reflect the merged fs100/dx100 MotoROS codebase.  I'll apply Eric's update once the reorg is complete.

**Comment by shaun-edwards** [comment]
@ted-miller, can you please verify that the issue raised by Thomas has been addressed in the motoman_driver package.

**Comment by ted-miller** [comment]
I will work with Eric to ensure the update has been made.

**Comment by ted-miller** [comment]
I'm told the issue has been addressed and the software in the motoman_driver package is up to date with this fix.
